---
# Best Practices - Ansible Documentation
# http://docs.ansible.com/playbooks_best_practices.html#directory-layout

- file: path={{ dest_dir }} state=directory

- name: setup layout designed for {{ role_names }}
  copy: src=./ dest={{ dest_dir }}
  notify:
    - show notes

